// File: layout.tsx
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import Link from 'next/link';
import { BookUserIcon } from 'lucide-react';
import { ClerkProvider, SignedIn } from '@clerk/nextjs';
import { SignedOut, SignInButton, SignUpButton } from '@clerk/nextjs';
import { Button } from '@/components/ui/button';
import UserDropdown from './user-dropdown';
import { Toaster } from 'sonner';

const poppins = Poppins({
	weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
	variable: '--font-poppins',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html lang='en'>
				<body className={`${poppins.variable} antialiased`}>
					<nav className='bg-primary p-4 text-white h-20 flex items-center justify-between'>
						<Link
							href='/'
							className='font-bold text-2xl flex gap-2 items-center'>
							<BookUserIcon className='text-yellow-500' /> LegacyPrints
						</Link>
						<div>
							<SignedOut>
								<div className='flex items-center'>
									<Button
										asChild
										variant='link'
										className='text-white cursor-pointer'>
										<SignInButton />
									</Button>
									<Button
										asChild
										variant='link'
										className='text-white cursor-pointer'>
										<SignUpButton />
									</Button>
								</div>
							</SignedOut>
							<SignedIn>
								<UserDropdown />
							</SignedIn>
						</div>
					</nav>
					{children}
					<Toaster richColors={true} />
				</body>
			</html>
		</ClerkProvider>
	);
}
