import dotenv from 'dotenv';
import { drizzle } from 'drizzle-orm/neon-http';
import { themesTable } from './schema';

dotenv.config({
	path: '.env.local',
});

const db = drizzle(process.env.DATABASE_URL!);

const themesSeedData: (typeof themesTable.$inferInsert)[] = [
	{
		name: 'Green Elegance',
		type: 'trifold',
		description:
			'A trifold theme featuring serene green theme with elegant floral designs, perfect for a peaceful memorial.',
		data: {
			pages: [
				{
					objects: [
						{
							src: '/dove-01.png',
							top: 141,
							left: 597.9353,
							name: 'dove_image_front',
							type: 'Image',
							angle: 4.7812,
							scaleX: 0.85,
							scaleY: 0.85,
							originX: 'left',
							originY: 'top',
							version: '6.0.0',
						},
						{
							src: '/brianna-richards-pic.png',
							top: 58,
							left: 654.4183,
							name: 'deceased_cover_photo',
							type: 'Image',
							scaleX: 0.75,
							scaleY: 0.75,
							originX: 'left',
							originY: 'top',
							version: '6.0.0',
						},
						{
							top: 51,
							fill: 'white',
							left: 613.9284,
							text: 'Celebration',
							type: 'IText',
							originX: 'left',
							originY: 'top',
							version: '6.0.0',
							fontSize: 21,
							fontStyle: 'italic',
							textAlign: 'center',
							fontFamily: 'Georgia',
						},
						{
							top: 71,
							fill: 'white',
							left: 645.9166,
							text: 'of',
							type: 'IText',
							originX: 'left',
							originY: 'top',
							version: '6.0.0',
							fontSize: 21,
							fontStyle: 'italic',
							textAlign: 'center',
							fontFamily: 'Georgia',
						},
						{
							top: 88,
							fill: {
								x1: 0,
								x2: 0,
								y1: 0,
								y2: 1,
								type: 'linear',
								colorStops: [
									{
										color: '#FFD700',
										offset: 0,
									},
									{
										color: '#DAA520',
										offset: 1,
									},
								],
							},
							left: 620.9253,
							text: 'Life',
							type: 'IText',
							originX: 'left',
							originY: 'top',
							version: '6.0.0',
							fontSize: 42,
							fontStyle: 'italic',
							textAlign: 'center',
							fontFamily: 'Aston Script Pro Bold',
						},
						{
							top: 129,
							fill: 'white',
							left: 645.4113,
							text: 'for',
							type: 'IText',
							originX: 'left',
							originY: 'top',
							version: '6.0.0',
							fontSize: 21,
							fontStyle: 'italic',
							textAlign: 'center',
							fontFamily: 'Georgia',
						},
						{
							top: 438.5,
							fill: {
								x1: 0,
								x2: 0,
								y1: 0,
								y2: 1,
								type: 'linear',
								colorStops: [
									{
										color: '#FFD700',
										offset: 0,
									},
									{
										color: '#DAA520',
										offset: 1,
									},
								],
							},
							left: 713.1705,
							name: 'name_of_deceased',
							text: '{{deceasedName}}',
							type: 'IText',
							originX: 'left',
							originY: 'top',
							version: '6.0.0',
							fontSize: 48,
							textAlign: 'center',
							fontFamily: 'Aston Script Pro Bold',
						},
						{
							top: 515.5,
							fill: {
								x1: 0,
								x2: 0,
								y1: 0,
								y2: 1,
								type: 'linear',
								colorStops: [
									{
										color: '#FFD700',
										offset: 0,
									},
									{
										color: '#DAA520',
										offset: 1,
									},
								],
							},
							left: 679.1635,
							name: 'sunrise',
							text: 'Sunrise',
							type: 'IText',
							originX: 'left',
							originY: 'top',
							version: '6.0.0',
							fontSize: 24,
							textAlign: 'center',
							fontFamily: 'Aston Script Pro Bold',
						},
						{
							top: 510.5,
							fill: {
								x1: 0,
								x2: 0,
								y1: 0,
								y2: 1,
								type: 'linear',
								colorStops: [
									{
										color: '#FFD700',
										offset: 0,
									},
									{
										color: '#DAA520',
										offset: 1,
									},
								],
							},
							left: 939.0936,
							name: 'sunset',
							text: 'Sunset',
							type: 'IText',
							originX: 'left',
							originY: 'top',
							version: '6.0.0',
							fontSize: 24,
							textAlign: 'center',
							fontFamily: 'Aston Script Pro Bold',
						},
						{
							top: 554,
							fill: '#FFFFFF',
							left: 638.9262,
							name: 'sunrise_date',
							text: '{{sunriseDate}}',
							type: 'IText',
							originX: 'left',
							originY: 'top',
							version: '6.0.0',
							fontSize: 22.5,
							textAlign: 'center',
							fontFamily: 'Georgia',
						},
						{
							top: 549,
							fill: '#FFFFFF',
							left: 906.8528,
							name: 'sunset_date',
							text: '{{sunsetDate}}',
							type: 'IText',
							originX: 'left',
							originY: 'top',
							version: '6.0.0',
							fontSize: 22.5,
							textAlign: 'center',
							fontFamily: 'Georgia',
						},
						{
							top: 600,
							fill: '#FFFFFF',
							left: 722.8982,
							name: 'service_date',
							text: '{{serviceDatetime}}',
							type: 'IText',
							originX: 'left',
							originY: 'top',
							version: '6.0.0',
							fontSize: 22.5,
							textAlign: 'center',
							fontFamily: 'Georgia',
						},
						{
							top: 663,
							fill: '#FFFFFF',
							left: 758.1508,
							name: 'front_church_address',
							text: '{{serviceLocation}}',
							type: 'IText',
							originX: 'left',
							originY: 'top',
							version: '6.0.0',
							fontSize: 20,
							textAlign: 'center',
							fontFamily: 'Georgia',
						},
						{
							top: 760,
							fill: '#FFFFFF',
							left: 531.25,
							name: 'front_officiant',
							text: 'Rev. James Carmichael — Officiating',
							type: 'IText',
							originX: 'left',
							originY: 'top',
							version: '6.0.0',
							fontSize: 20,
							fontStyle: 'italic',
							textAlign: 'center',
							fontFamily: 'Georgia',
						},
						{
							top: 0,
							fill: '#04291d',
							left: 76.2167,
							name: 'green_bar',
							type: 'Rect',
							width: 162.5,
							height: 637.5,
							opacity: 0.5,
							originX: 'left',
							originY: 'top',
							version: '6.0.0',
						},
						{
							top: 91,
							fill: {
								x1: 0,
								x2: 0,
								y1: 0,
								y2: 1,
								type: 'linear',
								colorStops: [
									{
										color: '#FFD700',
										offset: 0,
									},
									{
										color: '#DAA520',
										offset: 1,
									},
								],
							},
							left: 152.9436,
							name: 'left_poem_title',
							text: "God's Garden",
							type: 'IText',
							originX: 'left',
							originY: 'top',
							version: '6.0.0',
							fontSize: 37.5,
							textAlign: 'center',
							fontFamily: 'Aston Script Pro Bold',
							fontWeight: 'bold',
						},
						{
							top: 173,
							fill: '#FFFFFF',
							left: 123.9563,
							name: 'left_poem_text',
							text: 'God looked around His garden,\nAnd He found an empty place.\nHe then looked down upon the Earth\nAnd saw your precious face.\nHe put His arms around you\nAnd lifted you to rest.\nGod\'s garden must be beautiful;\nHe always takes the best.\nHe knew that you were suffering;\nHe knew you were in pain.\nHe knew you would never, ever\nGet well on Earth again.\nSo He closed your weary eyelids\nAnd whispered, "Peace be thine."\nThen He took you up to Heaven\nWith hands so gentle and kind.\nIt broke our hearts to lose you,\nBut you did not go alone.\nPart of us went with you\nThe day God welcomed you home.',
							type: 'IText',
							originX: 'left',
							originY: 'top',
							version: '6.0.0',
							fontSize: 18,
							fontStyle: 'italic',
							textAlign: 'center',
							fontFamily: 'Georgia',
							lineHeight: 1.4,
						},
					],
					version: '6.7.0',
					background: '/green-elegance-smol.jpg',
					backgroundImage: {
						src: '/green-elegance-smol.jpg',
						top: 0,
						fill: 'rgb(0,0,0)',
						left: -17.3409,
						type: 'Image',
						angle: 0,
						cropX: 0,
						cropY: 0,
						flipX: false,
						flipY: false,
						skewX: 0,
						skewY: 0,
						width: 1275,
						height: 825,
						scaleX: 0.9248,
						scaleY: 0.9248,
						shadow: null,
						stroke: null,
						filters: [],
						opacity: 1,
						originX: 'left',
						originY: 'top',
						version: '6.7.0',
						visible: true,
						fillRule: 'nonzero',
						paintFirst: 'fill',
						crossOrigin: 'anonymous',
						strokeWidth: 0,
						strokeLineCap: 'butt',
						strokeUniform: false,
						strokeLineJoin: 'miter',
						backgroundColor: '',
						strokeDashArray: null,
						strokeDashOffset: 0,
						strokeMiterLimit: 4,
						globalCompositeOperation: 'source-over',
					},
				},
				{
					objects: [
						{
							top: 65,
							fill: '#2c3e50',
							left: 666.8834,
							text: 'In Loving Memory',
							type: 'IText',
							angle: 0,
							flipX: false,
							flipY: false,
							skewX: 0,
							skewY: 0,
							width: 341.2969,
							height: 40.68,
							scaleX: 1,
							scaleY: 1,
							shadow: null,
							stroke: null,
							styles: [],
							opacity: 1,
							originX: 'left',
							originY: 'top',
							version: '6.7.0',
							visible: true,
							fillRule: 'nonzero',
							fontSize: 36,
							overline: false,
							pathSide: 'left',
							direction: 'ltr',
							fontStyle: 'normal',
							pathAlign: 'baseline',
							textAlign: 'center',
							underline: false,
							fontFamily: 'Georgia',
							fontWeight: 'bold',
							lineHeight: 1.16,
							paintFirst: 'fill',
							charSpacing: 0,
							linethrough: false,
							strokeWidth: 1,
							strokeLineCap: 'butt',
							strokeUniform: false,
							strokeLineJoin: 'miter',
							backgroundColor: '',
							pathStartOffset: 0,
							strokeDashArray: null,
							strokeDashOffset: 0,
							strokeMiterLimit: 4,
							textBackgroundColor: '',
							textDecorationThickness: 66.667,
							globalCompositeOperation: 'source-over',
						},
						{
							top: 416,
							fill: '#34495e',
							left: 781.8331,
							text: '{{deceasedName}}',
							type: 'IText',
							angle: 0,
							flipX: false,
							flipY: false,
							skewX: 0,
							skewY: 0,
							width: 132.9453,
							height: 31.64,
							scaleX: 1,
							scaleY: 1,
							shadow: null,
							stroke: null,
							styles: [],
							opacity: 1,
							originX: 'left',
							originY: 'top',
							version: '6.7.0',
							visible: true,
							fillRule: 'nonzero',
							fontSize: 28,
							overline: false,
							pathSide: 'left',
							direction: 'ltr',
							fontStyle: 'normal',
							pathAlign: 'baseline',
							textAlign: 'center',
							underline: false,
							fontFamily: 'Georgia',
							fontWeight: 'bold',
							lineHeight: 1.16,
							paintFirst: 'fill',
							charSpacing: 0,
							linethrough: false,
							strokeWidth: 1,
							strokeLineCap: 'butt',
							strokeUniform: false,
							strokeLineJoin: 'miter',
							backgroundColor: '',
							pathStartOffset: 0,
							strokeDashArray: null,
							strokeDashOffset: 0,
							strokeMiterLimit: 4,
							textBackgroundColor: '',
							textDecorationThickness: 66.667,
							globalCompositeOperation: 'source-over',
						},
						{
							top: 472,
							fill: '#7f8c8d',
							left: 731.855,
							text: 'April 30, 2025 - June 9, 2025',
							type: 'IText',
							angle: 0,
							flipX: false,
							flipY: false,
							skewX: 0,
							skewY: 0,
							width: 231.1611,
							height: 20.34,
							scaleX: 1,
							scaleY: 1,
							shadow: null,
							stroke: null,
							styles: [],
							opacity: 1,
							originX: 'left',
							originY: 'top',
							version: '6.7.0',
							visible: true,
							fillRule: 'nonzero',
							fontSize: 18,
							overline: false,
							pathSide: 'left',
							direction: 'ltr',
							fontStyle: 'normal',
							pathAlign: 'baseline',
							textAlign: 'center',
							underline: false,
							fontFamily: 'Arial',
							fontWeight: 'normal',
							lineHeight: 1.16,
							paintFirst: 'fill',
							charSpacing: 0,
							linethrough: false,
							strokeWidth: 1,
							strokeLineCap: 'butt',
							strokeUniform: false,
							strokeLineJoin: 'miter',
							backgroundColor: '',
							pathStartOffset: 0,
							strokeDashArray: null,
							strokeDashOffset: 0,
							strokeMiterLimit: 4,
							textBackgroundColor: '',
							textDecorationThickness: 66.667,
							globalCompositeOperation: 'source-over',
						},
						{
							top: 508,
							fill: '#7f8c8d',
							left: 728.8563,
							text: 'Service: June 10, 2025 at 3:14 PM',
							type: 'IText',
							angle: 0,
							flipX: false,
							flipY: false,
							skewX: 0,
							skewY: 0,
							width: 245.4844,
							height: 18.08,
							scaleX: 1,
							scaleY: 1,
							shadow: null,
							stroke: null,
							styles: [],
							opacity: 1,
							originX: 'left',
							originY: 'top',
							version: '6.7.0',
							visible: true,
							fillRule: 'nonzero',
							fontSize: 16,
							overline: false,
							pathSide: 'left',
							direction: 'ltr',
							fontStyle: 'normal',
							pathAlign: 'baseline',
							textAlign: 'center',
							underline: false,
							fontFamily: 'Arial',
							fontWeight: 'normal',
							lineHeight: 1.16,
							paintFirst: 'fill',
							charSpacing: 0,
							linethrough: false,
							strokeWidth: 1,
							strokeLineCap: 'butt',
							strokeUniform: false,
							strokeLineJoin: 'miter',
							backgroundColor: '',
							pathStartOffset: 0,
							strokeDashArray: null,
							strokeDashOffset: 0,
							strokeMiterLimit: 4,
							textBackgroundColor: '',
							textDecorationThickness: 66.667,
							globalCompositeOperation: 'source-over',
						},
						{
							top: 550,
							fill: '#7f8c8d',
							left: 782.8327,
							text: 'First Baptist Church',
							type: 'IText',
							angle: 0,
							flipX: false,
							flipY: false,
							skewX: 0,
							skewY: 0,
							width: 140.4844,
							height: 18.08,
							scaleX: 1,
							scaleY: 1,
							shadow: null,
							stroke: null,
							styles: [],
							opacity: 1,
							originX: 'left',
							originY: 'top',
							version: '6.7.0',
							visible: true,
							fillRule: 'nonzero',
							fontSize: 16,
							overline: false,
							pathSide: 'left',
							direction: 'ltr',
							fontStyle: 'normal',
							pathAlign: 'baseline',
							textAlign: 'center',
							underline: false,
							fontFamily: 'Arial',
							fontWeight: 'normal',
							lineHeight: 1.16,
							paintFirst: 'fill',
							charSpacing: 0,
							linethrough: false,
							strokeWidth: 1,
							strokeLineCap: 'butt',
							strokeUniform: false,
							strokeLineJoin: 'miter',
							backgroundColor: '',
							pathStartOffset: 0,
							strokeDashArray: null,
							strokeDashOffset: 0,
							strokeMiterLimit: 4,
							textBackgroundColor: '',
							textDecorationThickness: 66.667,
							globalCompositeOperation: 'source-over',
						},
						{
							src: '/brianna-richards-pic.png',
							top: 131,
							fill: 'rgb(0,0,0)',
							left: 739.8952,
							type: 'Image',
							angle: 0,
							cropX: 0,
							cropY: 0,
							flipX: false,
							flipY: false,
							skewX: 0,
							skewY: 0,
							width: 200,
							height: 250,
							scaleX: 1,
							scaleY: 1,
							shadow: null,
							stroke: null,
							filters: [],
							opacity: 1,
							originX: 'left',
							originY: 'top',
							version: '6.7.0',
							visible: true,
							fillRule: 'nonzero',
							paintFirst: 'fill',
							crossOrigin: null,
							strokeWidth: 0,
							strokeLineCap: 'butt',
							strokeUniform: false,
							strokeLineJoin: 'miter',
							backgroundColor: '',
							strokeDashArray: null,
							strokeDashOffset: 0,
							strokeMiterLimit: 4,
							globalCompositeOperation: 'source-over',
						},
					],
					version: '6.7.0',
					background: '/green-elegance-smol.jpg',
					backgroundImage: {
						src: '/green-elegance-smol.jpg',
						top: 0,
						fill: 'rgb(0,0,0)',
						left: -17.3409,
						type: 'Image',
						angle: 0,
						cropX: 0,
						cropY: 0,
						flipX: false,
						flipY: false,
						skewX: 0,
						skewY: 0,
						width: 1275,
						height: 825,
						scaleX: 0.9248,
						scaleY: 0.9248,
						shadow: null,
						stroke: null,
						filters: [],
						opacity: 1,
						originX: 'left',
						originY: 'top',
						version: '6.7.0',
						visible: true,
						fillRule: 'nonzero',
						paintFirst: 'fill',
						crossOrigin: 'anonymous',
						strokeWidth: 0,
						strokeLineCap: 'butt',
						strokeUniform: false,
						strokeLineJoin: 'miter',
						backgroundColor: '',
						strokeDashArray: null,
						strokeDashOffset: 0,
						strokeMiterLimit: 4,
						globalCompositeOperation: 'source-over',
					},
				},
			],
		},
	},
	{
		name: 'Green Elegance',
		type: 'bifold',
		description:
			'A bifold theme featuring serene green theme with elegant floral designs, perfect for a peaceful memorial.',
		data: {
			pages: [
				{
					objects: [
						{
							src: '/dove-01.png',
							top: 141,
							left: 597.9353,
							name: 'dove_image_front',
							type: 'Image',
							angle: 4.7812,
							scaleX: 0.85,
							scaleY: 0.85,
							originX: 'left',
							originY: 'top',
							version: '6.0.0',
						},
						{
							src: '/brianna-richards-pic.png',
							top: 58,
							left: 654.4183,
							name: 'deceased_cover_photo',
							type: 'Image',
							scaleX: 0.75,
							scaleY: 0.75,
							originX: 'left',
							originY: 'top',
							version: '6.0.0',
						},
						{
							top: 51,
							fill: 'white',
							left: 613.9284,
							text: 'Celebration',
							type: 'IText',
							originX: 'left',
							originY: 'top',
							version: '6.0.0',
							fontSize: 21,
							fontStyle: 'italic',
							textAlign: 'center',
							fontFamily: 'Georgia',
						},
						{
							top: 71,
							fill: 'white',
							left: 645.9166,
							text: 'of',
							type: 'IText',
							originX: 'left',
							originY: 'top',
							version: '6.0.0',
							fontSize: 21,
							fontStyle: 'italic',
							textAlign: 'center',
							fontFamily: 'Georgia',
						},
						{
							top: 88,
							fill: {
								x1: 0,
								x2: 0,
								y1: 0,
								y2: 1,
								type: 'linear',
								colorStops: [
									{
										color: '#FFD700',
										offset: 0,
									},
									{
										color: '#DAA520',
										offset: 1,
									},
								],
							},
							left: 620.9253,
							text: 'Life',
							type: 'IText',
							originX: 'left',
							originY: 'top',
							version: '6.0.0',
							fontSize: 42,
							fontStyle: 'italic',
							textAlign: 'center',
							fontFamily: 'Aston Script Pro Bold',
						},
						{
							top: 129,
							fill: 'white',
							left: 645.4113,
							text: 'for',
							type: 'IText',
							originX: 'left',
							originY: 'top',
							version: '6.0.0',
							fontSize: 21,
							fontStyle: 'italic',
							textAlign: 'center',
							fontFamily: 'Georgia',
						},
						{
							top: 438.5,
							fill: {
								x1: 0,
								x2: 0,
								y1: 0,
								y2: 1,
								type: 'linear',
								colorStops: [
									{
										color: '#FFD700',
										offset: 0,
									},
									{
										color: '#DAA520',
										offset: 1,
									},
								],
							},
							left: 713.1705,
							name: 'name_of_deceased',
							text: '{{deceasedName}}',
							type: 'IText',
							originX: 'left',
							originY: 'top',
							version: '6.0.0',
							fontSize: 48,
							textAlign: 'center',
							fontFamily: 'Aston Script Pro Bold',
						},
						{
							top: 515.5,
							fill: {
								x1: 0,
								x2: 0,
								y1: 0,
								y2: 1,
								type: 'linear',
								colorStops: [
									{
										color: '#FFD700',
										offset: 0,
									},
									{
										color: '#DAA520',
										offset: 1,
									},
								],
							},
							left: 679.1635,
							name: 'sunrise',
							text: 'Sunrise',
							type: 'IText',
							originX: 'left',
							originY: 'top',
							version: '6.0.0',
							fontSize: 24,
							textAlign: 'center',
							fontFamily: 'Aston Script Pro Bold',
						},
						{
							top: 510.5,
							fill: {
								x1: 0,
								x2: 0,
								y1: 0,
								y2: 1,
								type: 'linear',
								colorStops: [
									{
										color: '#FFD700',
										offset: 0,
									},
									{
										color: '#DAA520',
										offset: 1,
									},
								],
							},
							left: 939.0936,
							name: 'sunset',
							text: 'Sunset',
							type: 'IText',
							originX: 'left',
							originY: 'top',
							version: '6.0.0',
							fontSize: 24,
							textAlign: 'center',
							fontFamily: 'Aston Script Pro Bold',
						},
						{
							top: 554,
							fill: '#FFFFFF',
							left: 638.9262,
							name: 'sunrise_date',
							text: '{{sunriseDate}}',
							type: 'IText',
							originX: 'left',
							originY: 'top',
							version: '6.0.0',
							fontSize: 22.5,
							textAlign: 'center',
							fontFamily: 'Georgia',
						},
						{
							top: 549,
							fill: '#FFFFFF',
							left: 906.8528,
							name: 'sunset_date',
							text: '{{sunsetDate}}',
							type: 'IText',
							originX: 'left',
							originY: 'top',
							version: '6.0.0',
							fontSize: 22.5,
							textAlign: 'center',
							fontFamily: 'Georgia',
						},
						{
							top: 600,
							fill: '#FFFFFF',
							left: 722.8982,
							name: 'service_date',
							text: '{{serviceDatetime}}',
							type: 'IText',
							originX: 'left',
							originY: 'top',
							version: '6.0.0',
							fontSize: 22.5,
							textAlign: 'center',
							fontFamily: 'Georgia',
						},
						{
							top: 663,
							fill: '#FFFFFF',
							left: 758.1508,
							name: 'front_church_address',
							text: '{{serviceLocation}}',
							type: 'IText',
							originX: 'left',
							originY: 'top',
							version: '6.0.0',
							fontSize: 20,
							textAlign: 'center',
							fontFamily: 'Georgia',
						},
						{
							top: 760,
							fill: '#FFFFFF',
							left: 531.25,
							name: 'front_officiant',
							text: 'Rev. James Carmichael — Officiating',
							type: 'IText',
							originX: 'left',
							originY: 'top',
							version: '6.0.0',
							fontSize: 20,
							fontStyle: 'italic',
							textAlign: 'center',
							fontFamily: 'Georgia',
						},
						{
							top: 0,
							fill: '#04291d',
							left: 76.2167,
							name: 'green_bar',
							type: 'Rect',
							width: 162.5,
							height: 637.5,
							opacity: 0.5,
							originX: 'left',
							originY: 'top',
							version: '6.0.0',
						},
						{
							top: 91,
							fill: {
								x1: 0,
								x2: 0,
								y1: 0,
								y2: 1,
								type: 'linear',
								colorStops: [
									{
										color: '#FFD700',
										offset: 0,
									},
									{
										color: '#DAA520',
										offset: 1,
									},
								],
							},
							left: 152.9436,
							name: 'left_poem_title',
							text: "God's Garden",
							type: 'IText',
							originX: 'left',
							originY: 'top',
							version: '6.0.0',
							fontSize: 37.5,
							textAlign: 'center',
							fontFamily: 'Aston Script Pro Bold',
							fontWeight: 'bold',
						},
						{
							top: 173,
							fill: '#FFFFFF',
							left: 123.9563,
							name: 'left_poem_text',
							text: 'God looked around His garden,\nAnd He found an empty place.\nHe then looked down upon the Earth\nAnd saw your precious face.\nHe put His arms around you\nAnd lifted you to rest.\nGod\'s garden must be beautiful;\nHe always takes the best.\nHe knew that you were suffering;\nHe knew you were in pain.\nHe knew you would never, ever\nGet well on Earth again.\nSo He closed your weary eyelids\nAnd whispered, "Peace be thine."\nThen He took you up to Heaven\nWith hands so gentle and kind.\nIt broke our hearts to lose you,\nBut you did not go alone.\nPart of us went with you\nThe day God welcomed you home.',
							type: 'IText',
							originX: 'left',
							originY: 'top',
							version: '6.0.0',
							fontSize: 18,
							fontStyle: 'italic',
							textAlign: 'center',
							fontFamily: 'Georgia',
							lineHeight: 1.4,
						},
					],
					version: '6.7.0',
					background: '/green-elegance-smol.jpg',
					backgroundImage: {
						src: '/green-elegance-smol.jpg',
						top: 0,
						fill: 'rgb(0,0,0)',
						left: -17.3409,
						type: 'Image',
						angle: 0,
						cropX: 0,
						cropY: 0,
						flipX: false,
						flipY: false,
						skewX: 0,
						skewY: 0,
						width: 1275,
						height: 825,
						scaleX: 0.9248,
						scaleY: 0.9248,
						shadow: null,
						stroke: null,
						filters: [],
						opacity: 1,
						originX: 'left',
						originY: 'top',
						version: '6.7.0',
						visible: true,
						fillRule: 'nonzero',
						paintFirst: 'fill',
						crossOrigin: 'anonymous',
						strokeWidth: 0,
						strokeLineCap: 'butt',
						strokeUniform: false,
						strokeLineJoin: 'miter',
						backgroundColor: '',
						strokeDashArray: null,
						strokeDashOffset: 0,
						strokeMiterLimit: 4,
						globalCompositeOperation: 'source-over',
					},
				},
				{
					objects: [
						{
							top: 65,
							fill: '#2c3e50',
							left: 666.8834,
							text: 'In Loving Memory',
							type: 'IText',
							angle: 0,
							flipX: false,
							flipY: false,
							skewX: 0,
							skewY: 0,
							width: 341.2969,
							height: 40.68,
							scaleX: 1,
							scaleY: 1,
							shadow: null,
							stroke: null,
							styles: [],
							opacity: 1,
							originX: 'left',
							originY: 'top',
							version: '6.7.0',
							visible: true,
							fillRule: 'nonzero',
							fontSize: 36,
							overline: false,
							pathSide: 'left',
							direction: 'ltr',
							fontStyle: 'normal',
							pathAlign: 'baseline',
							textAlign: 'center',
							underline: false,
							fontFamily: 'Georgia',
							fontWeight: 'bold',
							lineHeight: 1.16,
							paintFirst: 'fill',
							charSpacing: 0,
							linethrough: false,
							strokeWidth: 1,
							strokeLineCap: 'butt',
							strokeUniform: false,
							strokeLineJoin: 'miter',
							backgroundColor: '',
							pathStartOffset: 0,
							strokeDashArray: null,
							strokeDashOffset: 0,
							strokeMiterLimit: 4,
							textBackgroundColor: '',
							textDecorationThickness: 66.667,
							globalCompositeOperation: 'source-over',
						},
						{
							top: 416,
							fill: '#34495e',
							left: 781.8331,
							text: '{{deceasedName}}',
							type: 'IText',
							angle: 0,
							flipX: false,
							flipY: false,
							skewX: 0,
							skewY: 0,
							width: 132.9453,
							height: 31.64,
							scaleX: 1,
							scaleY: 1,
							shadow: null,
							stroke: null,
							styles: [],
							opacity: 1,
							originX: 'left',
							originY: 'top',
							version: '6.7.0',
							visible: true,
							fillRule: 'nonzero',
							fontSize: 28,
							overline: false,
							pathSide: 'left',
							direction: 'ltr',
							fontStyle: 'normal',
							pathAlign: 'baseline',
							textAlign: 'center',
							underline: false,
							fontFamily: 'Georgia',
							fontWeight: 'bold',
							lineHeight: 1.16,
							paintFirst: 'fill',
							charSpacing: 0,
							linethrough: false,
							strokeWidth: 1,
							strokeLineCap: 'butt',
							strokeUniform: false,
							strokeLineJoin: 'miter',
							backgroundColor: '',
							pathStartOffset: 0,
							strokeDashArray: null,
							strokeDashOffset: 0,
							strokeMiterLimit: 4,
							textBackgroundColor: '',
							textDecorationThickness: 66.667,
							globalCompositeOperation: 'source-over',
						},
						{
							top: 472,
							fill: '#7f8c8d',
							left: 731.855,
							text: 'April 30, 2025 - June 9, 2025',
							type: 'IText',
							angle: 0,
							flipX: false,
							flipY: false,
							skewX: 0,
							skewY: 0,
							width: 231.1611,
							height: 20.34,
							scaleX: 1,
							scaleY: 1,
							shadow: null,
							stroke: null,
							styles: [],
							opacity: 1,
							originX: 'left',
							originY: 'top',
							version: '6.7.0',
							visible: true,
							fillRule: 'nonzero',
							fontSize: 18,
							overline: false,
							pathSide: 'left',
							direction: 'ltr',
							fontStyle: 'normal',
							pathAlign: 'baseline',
							textAlign: 'center',
							underline: false,
							fontFamily: 'Arial',
							fontWeight: 'normal',
							lineHeight: 1.16,
							paintFirst: 'fill',
							charSpacing: 0,
							linethrough: false,
							strokeWidth: 1,
							strokeLineCap: 'butt',
							strokeUniform: false,
							strokeLineJoin: 'miter',
							backgroundColor: '',
							pathStartOffset: 0,
							strokeDashArray: null,
							strokeDashOffset: 0,
							strokeMiterLimit: 4,
							textBackgroundColor: '',
							textDecorationThickness: 66.667,
							globalCompositeOperation: 'source-over',
						},
						{
							top: 508,
							fill: '#7f8c8d',
							left: 728.8563,
							text: 'Service: June 10, 2025 at 3:14 PM',
							type: 'IText',
							angle: 0,
							flipX: false,
							flipY: false,
							skewX: 0,
							skewY: 0,
							width: 245.4844,
							height: 18.08,
							scaleX: 1,
							scaleY: 1,
							shadow: null,
							stroke: null,
							styles: [],
							opacity: 1,
							originX: 'left',
							originY: 'top',
							version: '6.7.0',
							visible: true,
							fillRule: 'nonzero',
							fontSize: 16,
							overline: false,
							pathSide: 'left',
							direction: 'ltr',
							fontStyle: 'normal',
							pathAlign: 'baseline',
							textAlign: 'center',
							underline: false,
							fontFamily: 'Arial',
							fontWeight: 'normal',
							lineHeight: 1.16,
							paintFirst: 'fill',
							charSpacing: 0,
							linethrough: false,
							strokeWidth: 1,
							strokeLineCap: 'butt',
							strokeUniform: false,
							strokeLineJoin: 'miter',
							backgroundColor: '',
							pathStartOffset: 0,
							strokeDashArray: null,
							strokeDashOffset: 0,
							strokeMiterLimit: 4,
							textBackgroundColor: '',
							textDecorationThickness: 66.667,
							globalCompositeOperation: 'source-over',
						},
						{
							top: 550,
							fill: '#7f8c8d',
							left: 782.8327,
							text: 'First Baptist Church',
							type: 'IText',
							angle: 0,
							flipX: false,
							flipY: false,
							skewX: 0,
							skewY: 0,
							width: 140.4844,
							height: 18.08,
							scaleX: 1,
							scaleY: 1,
							shadow: null,
							stroke: null,
							styles: [],
							opacity: 1,
							originX: 'left',
							originY: 'top',
							version: '6.7.0',
							visible: true,
							fillRule: 'nonzero',
							fontSize: 16,
							overline: false,
							pathSide: 'left',
							direction: 'ltr',
							fontStyle: 'normal',
							pathAlign: 'baseline',
							textAlign: 'center',
							underline: false,
							fontFamily: 'Arial',
							fontWeight: 'normal',
							lineHeight: 1.16,
							paintFirst: 'fill',
							charSpacing: 0,
							linethrough: false,
							strokeWidth: 1,
							strokeLineCap: 'butt',
							strokeUniform: false,
							strokeLineJoin: 'miter',
							backgroundColor: '',
							pathStartOffset: 0,
							strokeDashArray: null,
							strokeDashOffset: 0,
							strokeMiterLimit: 4,
							textBackgroundColor: '',
							textDecorationThickness: 66.667,
							globalCompositeOperation: 'source-over',
						},
						{
							src: '/brianna-richards-pic.png',
							top: 131,
							fill: 'rgb(0,0,0)',
							left: 739.8952,
							type: 'Image',
							angle: 0,
							cropX: 0,
							cropY: 0,
							flipX: false,
							flipY: false,
							skewX: 0,
							skewY: 0,
							width: 200,
							height: 250,
							scaleX: 1,
							scaleY: 1,
							shadow: null,
							stroke: null,
							filters: [],
							opacity: 1,
							originX: 'left',
							originY: 'top',
							version: '6.7.0',
							visible: true,
							fillRule: 'nonzero',
							paintFirst: 'fill',
							crossOrigin: null,
							strokeWidth: 0,
							strokeLineCap: 'butt',
							strokeUniform: false,
							strokeLineJoin: 'miter',
							backgroundColor: '',
							strokeDashArray: null,
							strokeDashOffset: 0,
							strokeMiterLimit: 4,
							globalCompositeOperation: 'source-over',
						},
					],
					version: '6.7.0',
					background: '/green-elegance-smol.jpg',
					backgroundImage: {
						src: '/green-elegance-smol.jpg',
						top: 0,
						fill: 'rgb(0,0,0)',
						left: -17.3409,
						type: 'Image',
						angle: 0,
						cropX: 0,
						cropY: 0,
						flipX: false,
						flipY: false,
						skewX: 0,
						skewY: 0,
						width: 1275,
						height: 825,
						scaleX: 0.9248,
						scaleY: 0.9248,
						shadow: null,
						stroke: null,
						filters: [],
						opacity: 1,
						originX: 'left',
						originY: 'top',
						version: '6.7.0',
						visible: true,
						fillRule: 'nonzero',
						paintFirst: 'fill',
						crossOrigin: 'anonymous',
						strokeWidth: 0,
						strokeLineCap: 'butt',
						strokeUniform: false,
						strokeLineJoin: 'miter',
						backgroundColor: '',
						strokeDashArray: null,
						strokeDashOffset: 0,
						strokeMiterLimit: 4,
						globalCompositeOperation: 'source-over',
					},
				},
			],
		},
	},
];

async function main() {
	await db.insert(themesTable).values(themesSeedData);
}

main();
